### ISSUE TITLE
All workspaces being created even if empty

### ISSUE THREAD

**Issue by nikhilc1527** [Duckonaut/split-monitor-workspaces#125]
It seems like the fix to #122 has now made it so that all workspaces on every monitor are being created, even when empty. I cloned the repo and reverted the change from commit 5ba1e2e, and it worked. I'm not sure about persistent workspaces though, and if I have broken them again, which is why I'm creating an issue for this. I can provide any additional info that anyone needs

**Comment by zjeffer** [comment]
Can you describe your display setup and which config options you're using?

#122 is supposed to ensure that when `enable_persistent_workspaces` is `false`, each monitor is focused on the correct mapped workspace at boot. Say you start Hyprland with this option set to false and have 3 monitors, the monitors would each get one workspace with ID 1 for the first monitor, 2 for the second, 3 for the third. Say you're using this plugin configured with 3 workspaces per monitor, you'd want those 3 monitors to have [1, 2, 3] for the 1st monitor, [4, 5, 6] for the second and [7, 8, 9] for the third. #122 ensures that even with persistent workspaces disabled, it still ensures that when you boot, your first workspace is focused on workspace 1, your second monitor on workspace 4, and your third monitor on workspace 7. 

It's not supposed to create *all* workspaces on each monitor, only the first one.

**Comment by vpzomtrrfrt** [comment]
I'm using the default configuration and I'm seeing this issue.

**Comment by zjeffer** [comment]
> I'm using the default configuration and I'm seeing this issue.

With the default configuration, all workspaces are supposed to be created, because persistent workspaces is enabled. If you don't want that, set `enable_persistent_workspaces` to false.

**Comment by nikhilc1527** [comment]
I see. I feel like this shouldn't be default behavior, or at least this behavior has changed since the last commit. Just enabling the handling of persistent workspaces shouldnt create all of them, if i never actually set any of them to be persistent. Please correct me if I'm understanding wrong

**Comment by zjeffer** [comment]
> Just enabling the handling of persistent workspaces shouldnt create all of them, if i never actually set any of them to be persistent

I'm not sure I fully understand this, why would *you* set them persistent? The plugin takes care of this when you set enable_persistent_workspaces to be `true`. 
If I understand correctly, you want to make your workspaces persistent, without actually creating them?

> I feel like this shouldn't be default behavior, or at least this behavior has changed since the last commit.

The behaviour has changed in #111, where previously if you wanted persistent workspaces managed by the plugin, you had to source the file `/tmp/hyprland-workspace-rules` (generated by the plugin at initialization) in your Hyprland config. This was kind of an ugly solution that was greatly improved by that PR, but the PR also made persistent workspaces management enabled by default.

IIRC, #122 only fixes some behaviour at boot when persistent workspaces is *not* enabled.

**Comment by nikhilc1527** [comment]
Sorry, I meant that I didn't set persistent to true, but it is set to true by default, which is different from the default behavior in base Hyprland as well as (I'm pretty sure) the default behavior from before this commit. Of course, now i knoe my entire problem could have been solved by simply setting persistent workspaces to false, but I'm just discussing general ux

**Comment by nikhilc1527** [comment]
Although I guess now my issue is that a default of managing persistent workspaces is fine, but managing them shouldn't mean that all workspaces are persistent by default. I could also be misunderstanding the entire feature wrong, maybe this is intended behavior and I just have to set the option to false if I don't want it

**Comment by zjeffer** [comment]
Here's how I intended it:

* In the config, you choose a certain amount of workspaces you want to access per monitor (I use 5)
* When Hyprland boots, waybar shows which workspaces belong to which monitor. For example: my second monitor has workspaces 6-10, of which 6 is currently selected, and 8 has a window. The rest are empty: 
![image](https://github.com/user-attachments/assets/6df2b58a-e31a-41c2-9658-73d9ddba3fdb)
* This way, the waybar workspaces module never changes width: it always shows 5 workspaces regardless of which are empty or not. 
* In my example, when you use hyprctl to send a window to the workspace with ID=9, you know for a fact that regardless of which monitor you are on, it will send it to the 4th workspace on the second monitor. 

Before Hyprland, I used to use `bspwm` with `polybar`, which works exactly like this: each monitor has a certain amount of workspaces, and polybar shows each workspace. 

Say the user is on monitor one, workspace 5 (the last workspace on that monitor) and uses `hyprctl dispatch workspace +2`. 
If we don't create all persistent workspaces at plugin initialization, workspace 7 won't exist on the second monitor yet. Instead, it would now be created by hyprctl on the first monitor. Suddenly you have 6 workspaces on monitor 1, not what you wanted.
With the current state of this plugin, executing that `hyprctl` command will move focus to the already existing workspace on monitor 2 (because we created it at initialization).

---

I don't really understand in which scenario you want the plugin to manage persistent workspaces, without creating them and making them persistent? Can you explain this further?

**Comment by nikhilc1527** [comment]
I see, I now understand my confusion. How I've always used workspaces, on dwm before and now Hyprland, was that only the workspaces that have windows open in them would be created, and therefore shown on the panel bar.
![image](https://github.com/user-attachments/assets/b930ee61-5e6a-4416-afe0-4168b05dda0e)
This is also how hyprland (without this plugin) works by default, if no workspace rules are set. I guess I misunderstood the config option "managing persistent workspaces", and didn't realize that creating all workspaces was intended behavior. I assumed that it just meant that whatever workspaces were set as persistent in hyprland configs were still going to be persistent with this plugin loaded. Maybe a bit of clarification in the docs, to indicate that all workspaces will be created by default?
