### ISSUE TITLE
"split-workspace, empty" should spawn workspace with different ID

### ISSUE THREAD

**Issue by johnhowe** [Duckonaut/split-monitor-workspaces#31]
I am using the following bind:
`bind = $mainMod, BackSpace, split-workspace, empty`

if called on the _second_ monitor, the next empty workspace from the _first_ monitor's workspaces is spawned on the _second_ monitor

**Comment by CRAG666** [comment]
Same problem

**Comment by zjeffer** [comment]
I don't fully understand the issue. Is the behaviour of the plugin's `split-workspace` dispatcher different from Hyprland's `workspace` dispatcher when passing `emtpy` as the workspace?

**Comment by thomasave** [comment]
@zjeffer I wanted to provide some clarification, since I'm also encountering this issue. 
Imagine we have the following monitors with corresponding workspaces:

Monitor 0: Workspace 1, Workspace 2  
Monitor 1: Workspace 11, Workspace 12

Monitor 1 is currently focused on Workspace 11. 
When pressing the key that is bound to `split-workspace, empty`, this creates the new Workspace 3 on Monitor 1.
What we expect is that the new workspace is 13 instead of 3.
That way, when using `split-workspace, 3` when focused on Workspace 11, we would switch back to Workspace 13 that was created using `split-workspace, empty` earlier.
I hope this clarifies the issue.

**Comment by zjeffer** [comment]
Ah, I understand now. I'll look into this.
